typography_spectrum: 0.5475206032861024
color:
  brandStrength: 0.872868541162461
  lightness: 0.8843976585194468
  saturation: 0.6864600526168942
  rhythmicContrast: 0.885308533674106
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.587947849649936
author:
  name: Spazi Consonanti
  email: studio@spaziconsonanti.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/711a4421-5471-4232-a1c1-04b22135a660.jpg
name: Spazi Consonanti
navigation:
  - name: About
    id: 89385d3c-c721-4ab3-a291-8ec53194ff68
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/edb889f6-2908-4dd1-841f-15df64542fc9.jpg
title: SPAZI CONSONANTI
description: 'Architecture, Restoration, Storytelling, Heritage'
