typography_spectrum: 0.4253116410691291
color:
  brandStrength: 0.5564922315534204
  lightness: 0.623440325492993
  saturation: 0.5661493006628007
  rhythmicContrast: 0.7992323315702379
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.8812716118991375
author:
  name: Spazi Consonanti
  email: studio@spaziconsonanti.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/711a4421-5471-4232-a1c1-04b22135a660.jpg
name: Spazi Consonanti
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/edb889f6-2908-4dd1-841f-15df64542fc9.jpg
title: SPAZI CONSONANTI
description: 'Architecture, Restoration, Storytelling, Heritage'
